(add-hook 'sql-mode-hook  (lambda ()
                            (let ((buf (current-buffer))
                                  (window-to-comeback (selected-window)))
                              (sql-postgres)
                              (select-window window-to-comeback)
                              (switch-to-buffer buf)
                              (sql-set-product "postgres")
                              (sql-set-sqli-buffer))))
